"""
Ryan Pranantyo
EOS, May 2025

a short script to plot rupture model generated by fakequakes MudPy
"""
import os, sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import argparse
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('--rupture_model', type = str,
                    default = 'sample.rupture.rupt',
                    help = 'a rupture model file generated by fakequakes, eg. subduction.000001.rupt')
parser.add_argument('--where_to_save', type = str,
                    default = './',
                    help = 'path to save the plot')
args = parser.parse_args()


rupture_model = Path(args.rupture_model)
fname = rupture_model.name.split('.')
fname = '_'.join(fname)

### configure a dataframe to make easy
columns = ['no', 'lon', 'lat', 'z', 'strike', 'dip', 'rise', 'dura', 'ss_slip', 'ds_slip', 'ss_len', 'ds_len', 'rupt_time', 'rigidity', 'velocity']
params = np.loadtxt(rupture_model)
df = pd.DataFrame(data = params, columns = columns)
df['no'] = df['no'].astype(int)
df['slip'] = np.sqrt(df['ss_slip'] ** 2 + df['ds_slip'] ** 2)

### plotting
fig = plt.figure(constrained_layout = True)
ax = fig.add_subplot(1,1,1, projection=ccrs.PlateCarree())
ax.coastlines()
slip = ax.scatter(df['lon'], df['lat'], c=df['slip'], 
                  vmin = 0, vmax = df['slip'].max())
cb = fig.colorbar(slip, pad=0)
cb.ax.set_ylabel('total slip (m)')
ax.set_xlim(df['lon'].min()-2, df['lon'].max()+2)
ax.set_ylim(df['lat'].min()-2, df['lat'].max()+2)
fout = os.path.join(args.where_to_save, f'{fname}.png')
fig.savefig(fout)
plt.close()
