#PBS -N combine_footprints
#PBS -P eos_luca.dalzilio
#PBS -q qamd_wfly
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=1

cd $PBS_O_WORKDIR

source /home/ignatius.pranantyo/.bashrc

~/apps/miniconda3/bin/activate 
conda activate tsunamis_py39

time python -W ignore generate_tsunami_footprint_offshore.py --SFFM_model /home/ignatius.pranantyo/Tsunamis/Stochastic__Sumatera_Java/OUTPUTS/stochastic_slips__sumatera_jawa__slab2__edited/stochastic_sources__Mw_8.400000__Lon_107.288800__Lat_-7.132900__table_simplified.csv
