"""
Ryan Pranantyo
EOS, March 2025

unit source generated by RPTHA is in GeoTIFF,
whereas JAGURS requires a displacement file in a grd format.

This script is used to do a simple conversion, 
at the same time, can be used to convert any displacement file from GTiff to a grd file
"""
import os, sys
import numpy as np
import rioxarray
import argparse
from pathlib import Path

def convert(args):
    """ procedures :
    1. convert GTiff to a grd netcdf file
    2. cut and resample to desired grid_bbox
    """
    print(args)
    where_to_save = Path(args.displacement_outdir)
    where_to_save.mkdir(exist_ok = True)

    gtiff = Path(args.gtiff_unitsource)
    fname = gtiff.name[:-4]
    ### convert to gtd netcdf
    cmd = f"gdal_translate {args.gtiff_unitsource} -of NetCDF {where_to_save}/{fname}_tmp.grd"
    os.system(cmd)
    #gtiff = rioxarray.open_rasterio(args.gtiff_unitsource)
    #gtiff.rio.to_raster(f"{where_to_save}/{fname}_tmp.grd")
    #gtiff.close()

    bbox = args.grid_bbox
    xmin, xmax, ymin, ymax, res = bbox[0], bbox[1], bbox[2], bbox[3], bbox[4]
    ### cut and resample
    cmd = f"gmt grdcut {where_to_save}/{fname}_tmp.grd -R{xmin}/{xmax}/{ymin}/{ymax} -N0 -G{where_to_save}/{fname}_tmp_cut.grd"
    os.system(cmd)
    cmd = f"gmt grdsample {where_to_save}/{fname}_tmp_cut.grd -R{xmin}/{xmax}/{ymin}/{ymax} -I{res}/{res} -T -G{where_to_save}/{fname}.grd=10"
    os.system(cmd)

    ### cleaning up
    cmd = f"rm -f {where_to_save}/*tmp*"
    os.system(cmd)
    
    return

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--gtiff_unitsource", type=str,
            default = "/home/ignatius.pranantyo/Tsunamis/Stochastic__Sumatera_Java/OUTPUTS/Unit_source_data/sumatera_jawa__slab2__edited/sumatera_jawa__slab2__edited_2_83.tif",
            help = "displacement file in GTiff")
    parser.add_argument("--grid_bbox", type=float, nargs="+",
            default = [102.000, 117.066, -12.500, -3.752, 0.027],
            help = "disp grd file for JAGURS: xmin, xmax, ymin, ymax, resolution in degree")
    parser.add_argument("--displacement_outdir", type=str,
            default = "/home/ignatius.pranantyo/Tsunamis/Stochastic__Sumatera_Java/jagurs_runs/uji_coba/unit_sources_gf/unit_sources__grid_2700m/unit_source__2_83",
            help = "where to save grd file")
    args = parser.parse_args()
    convert(args)
