#!/bin/bash
#PBS -N pts_prep
#PBS -P eos_luca.dalzilio
#PBS -q qintel_wfly
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=8:mem=64g

#module load gnu/gcc-12.3
#module load hdf5/1.14.3-intel2023-parallel

source /home/ignatius.pranantyo/.bashrc
~/apps/miniconda3/bin/activate
#conda activate gmt

cd $PBS_O_WORKDIR

#conda activate gmt
#python -W ignore dem_blending.py



conda activate tsunamis_py39
python -W ignore topo_correction.py

#gmt blockmean base_dem__no_adjustment.pts -I1s/1s -V -R105/117/-9/-5 > blockmean_1s__no_adjustment.pts

#gmt surface blockmean_1s__no_adjustment.pts -I1s/1s -T0.73 -V -Dsoftbreaklines_garpan_20250408.pts -Lu30 -Gdem__jawabalilombok_deltadtm__no_adjustment.grd -R105.01/116.99/-8.99/-5.


