#!/bin/bash
#PBS -N dem_filling
#PBS -P eos_luca.dalzilio
#PBS -q qintel_wfly
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=8:mem=64g

#module load gnu/gcc-12.3
#module load hdf5/1.14.3-intel2023-parallel

source /home/ignatius.pranantyo/.bashrc
~/apps/miniconda3/bin/activate
#conda activate gmt

cd $PBS_O_WORKDIR

conda activate gmt

python -W ignore dem_fill.py

#gmt grdfill /home/ignatius.pranantyo/DATA/working_deltadtm/blended__batnas_deltadtm__correctedby-0.0m__res1s/blend_dem.grd -Ag/scratch/ignatius.pranantyo/DATA/TanahAirIndonesia/BATNAS_v1-5-0.grd -G/home/ignatius.pranantyo/DATA/working_deltadtm/blended__batnas_deltadtm__correctedby-0.0m__res1s/blend_dem_filled.grd=nf


#python -W ignore dem_blending.py

